config/routes.rb
Rails.application.routes.draw do
  get 'games/new', to: 'games#new', as: 'new_game'
  post 'games/score', to: 'games#score'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    # display a new random grid and a form
    @letters = Array.new(10) { ('A'..'Z').to_a.sample }
  end

  def score
    # form will be submitted (with POST) to the score action.
    @word = params[:word].upcase
    @letters = params[:letters]

    if !word_in_grid?(@word, @letters)
      @result = "Sorry, but #{@word} cannot be built out of #{formatted_letters(@letters)}."
    elsif !valid_english_word?(@word)
      @result = "#{@word} is valid according to the grid, but is not a valid English word."
    else
      @result = "#{@word} is valid according to the grid and is an English word."
    end
  end

  private

  def word_in_grid?(word, grid)
    word.chars.all? { |char| word.count(char) <= grid.count(char) }
  end

  def formatted_letters(letters)
    letters.join(', ')
  end

  require 'net/http'
  require 'json'

  def valid_english_word?(word)
    uri = URI("https://wagon-dictionary.herokuapp.com/#{word}")
    response = Net::HTTP.get(uri)
    parsed_response = JSON.parse(response)
    parsed_response['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game:</h1>
<ul>
  <% @letters.each do |letter| %>
    <li><%= letter %></li>
  <% end %>
</ul>
<h2>What is the longest word you can find?</h2>
<form action="/games/score" method="post" data-turbo="false">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <% @letters.each do |letter| %>
    <%= hidden_field_tag 'letters[]', letter %>
  <% end %>
  <input type="text" name="word">
  <input type="submit" value="Play">
</form>

app/views/games/score.html.erb
<h1 class="mb-4">Result</h1>
<p class="lead"><%= @result %></p>
<%= link_to "New Game", new_game_path, class: "btn btn-primary mt-3" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>